// Code generated by "stringer -type=AuthorizationState"; DO NOT EDIT.

package portal

import "fmt"

const _AuthorizationState_name = "AuthorizationPendingAuthorizationAccepted"

var _AuthorizationState_index = [...]uint8{0, 20, 41}

func (i AuthorizationState) String() string {
	if i < 0 || i >= AuthorizationState(len(_AuthorizationState_index)-1) {
		return fmt.Sprintf("AuthorizationState(%d)", i)
	}
	return _AuthorizationState_name[_AuthorizationState_index[i]:_AuthorizationState_index[i+1]]
}
